### ISSUE TITLE
Either Disable or Fix Dark Mode

### ISSUE THREAD

**Issue by petersterne** [Stage-Whisper/Stage-Whisper#14]
Running stagewhisper through poetry while dark mode is active on MacOS causes this:

<img width="609" alt="Dark Mode on MacOS 2022-09-25" src="https://user-images.githubusercontent.com/28406666/192171618-769090c9-4747-4d8c-bb5e-f1aef2faa3a6.png">

Can we just fully disable dark mode or is this an issue where Gooey is automatically going to try to enter dark mode if the OS is in dark mode? The former is not a big deal, since we can just disable dark mode for now. The latter would be a very big problem.

**Comment by harrislapiroff** [comment]
We cannot disable dark mode :(

**Comment by harrislapiroff** [comment]
We *might* be able to change the label text. It's a little hackish but there's a label color and help color option for each field, so we could just make sure we *always* pass explicit color options to each field based on dark mode status.

https://github.com/chriskiehl/Gooey/blob/master/docs/Gooey-Options.md#global-style--layout-options

**Comment by petersterne** [comment]
Input color is white, right? So it at least shows up. OK, let's try making the label and help color white if it's in dark mode (or should the help color be like a whitish grey?) and see if that fixes the problem.

**Comment by mattahorton** [comment]
I'd be happy to try my hand at this. This was the first issue I encountered.

**Comment by mattahorton** [comment]
Fixed 🥳
