### ISSUE TITLE
OS-specific default output directory

### ISSUE THREAD

**Issue by harrislapiroff** [Stage-Whisper/Stage-Whisper#23]
Let's have the output directory default to an OS-specific reasonable default. For example on macOS this should be `~/Documents/`. The current default of `.` isn't tenable since I think that would cause files to generate inside the application bundle.

**Comment by petersterne** [comment]
What's the behavior if we specify a folder that does not exist? Will it create the folder the first time it's run or just crash?

If it creates a new folder, I'd recommend `~/Documents/Transcripts/` but if the directory needs to already exist, I think `~/Documents/` makes sense.

**Comment by crazy4pi314** [comment]
Would it be reasonable to put it in the same directory as the media selected by default? That would be what I would have expected an app to do if I don't tell it where to put things.

**Comment by petersterne** [comment]
Looking at the whisper code, it looks like if you specify an output directory that doesn't exist, then whisper will automatically create it (and any intermediate directories that also don't exist)
`os.makedirs(output_dir, exist_ok=True)`
https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L281

**Comment by crazy4pi314** [comment]
Yea

> Looking at the whisper code, it looks like if you specify an output directory that doesn't exist, then whisper will automatically create it (and any intermediate directories that also don't exist) `os.makedirs(output_dir, exist_ok=True)` https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L281

Yeah, so seems like it's ok to close this with the resolution: Output directories are relative to the input files, and if the output location doesn't exists, it will make it. Feel free to re-open if I am missing something 👍
