### ISSUE TITLE
Separate output and logging

### ISSUE THREAD

**Issue by harrislapiroff** [Stage-Whisper/Stage-Whisper#6]
Right now they get combined into a single shell. We should separate them, possibly by making it easy to direct output to a file? (Ultimately it would be nice to display just output in the interface, but I don't think we'll get there with Gooey.)
<img width="915" alt="Screen Shot 2022-09-25 at 1 58 35 AM" src="https://user-images.githubusercontent.com/296631/192130519-88747811-ee24-4957-811a-a08f554def17.png">

**Comment by petersterne** [comment]
I think that Whisper by default outputs to stdout and two files: filename.txt (just the transcribed text) and filename.vtt (timestamped text in VTT format, identical to stdout).

**Comment by harrislapiroff** [comment]
@petersterne That's correct. And that's what happens in our Gooey interface too—it outputs to the visible console *and* outputs files to the specified output dir.

One other thought is I wonder if we can cause output dir to default to a standard option for each OS (e.g., `~/Documents/` for macOS). I think `.` is not going to be a useful default once this is packaged as a binary.

**Comment by harrislapiroff** [comment]
This ticket was specific to the retired gooey approach—no longer relevant.
