### ISSUE TITLE
Poor transcription viewer performance

### ISSUE THREAD

**Issue by oenu** [Stage-Whisper/Stage-Whisper#72]
>  https://github.com/Stage-Whisper/Stage-Whisper/pull/71#issuecomment-1272010111

Im going to be looking into making it a table component as current approach is difficult to read and very heavy on the system, will make a new branch for this

_Originally posted by @oenu in https://github.com/Stage-Whisper/Stage-Whisper/issues/71#issuecomment-1272012338_

**Comment by sawhney17** [comment]
If you haven't started, I can take this today.
